name: Caller Workflow
on:
    workflow_dispatch:
        inputs:
            name:
                type: string
                default: Hari
                description: Enter name
jobs:
    call-workflow:
        uses: ./.github/workflows/reusable-workflow.yml
        with:
            name: "${{ inputs.name }}"
        secrets:
            my_token: ${{ secrets.MY_TOKEN }}