name: Caller Workflow
on:
    workflow_dispatch:
        inputs:
            name:
                type: string
                default: Hari
                description: Enter name
            skip_tests:
                type: boolean
                description: Skip test cases?
jobs:
    print-boolean:
        runs-on: ubuntu-latest
        steps:
            - name: Print Boolean Value
              run: echo "${{ inputs.skip_tests }}"
    call-workflow:
        uses: ./.github/workflows/reusable-workflow.yml
        with:
            name: "${{ inputs.name }}"
        secrets:
            my_token: ${{ secrets.MY_TOKEN }}