name: Hello Matrix Build

on: [push]

jobs:
  say-hello:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]

    steps:
      - name: Print Hello World
        run: echo "Hello from ${{ matrix.os }} using Node.js ${{ matrix.node }}"
