name: This is reusable workflow
on: 
    workflow_call:
        inputs:
            name:
                required: true
                type: string
        secrets:
            my_token:
                required: true

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome
              run: |
                echo "Hello, ${{ inputs.name }} Welcome from reusable workflows!"
                ehco "The secret is ${{ secrets.my_token }} "